# Site settings
name: Neha Desaraju
title: neha desaraju.
description: Creative, activist, & aspiring data analyst focused on new solutions for social justice
url: https://nehadesaraju.github.io/
baseurl: ''
email: neha.desaraju@gmail.com
cover: https://nehadesaraju.github.io/img/og.png
logo: https://nehadesaraju.github.io/img/emojis/technologist.png
resume: https://nehadesaraju.github.io/resume.pdf
social:
  - title: email
    url: mailto:nehadesaraju@gmail.com
  - title: twitter
    url: https://twitter.com/nehadesaraju
  - title: instagram
    url: https://instagram.com/nehadesaraju
  - title: linkedin
    url: https://www.linkedin.com/in/nehadesaraju

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
